### ISSUE TITLE
Add test for known malicious urls as well

### ISSUE THREAD

**Issue by Fitblip** [Phillipmartin/virustotal2#2]
Is probably going to be tricky, but pulling something down dynamically from Phishtank/etc should give a good mechanism to make sure there's as near 100% coverage as possible.

**Comment by Fitblip** [comment]
Crap. Missed the milestone button! Linking.

**Comment by Phillipmartin** [comment]
yeah, I thought about that but that doesn't actually test any code paths that a query for www.google.com doesn't hit (at least on the module side).

**Comment by Fitblip** [comment]
Ah, cool. Closing.
