### ISSUE TITLE
Get rid of `postfile` class

### ISSUE THREAD

**Issue by Fitblip** [Phillipmartin/virustotal2#3]
The Requests library can do multipart forms natively, and that class makes me sad (ThIs_Is_tHe_bouNdaRY_?).

http://stackoverflow.com/questions/12385179/how-to-send-a-multipart-form-data-with-requests-in-python

It also doesn't adhere to standard class inheritance (not that it needs to with all staticmethods), and a few other issues, but since it's only used in one place I think it can be easily removed.

**Comment by Phillipmartin** [comment]
yeah that class made me sad too.  that's what I get for being lazy and copy/pasting stuff from virustotal

**Comment by Fitblip** [comment]
Cool, I'll probably crank that out tonight and submit a PR.
