### ISSUE TITLE
Tests don't run on windows

### ISSUE THREAD

**Issue by Fitblip** [Phillipmartin/virustotal2#6]
Should be able to call the test suite directly or through `setup.py test`

Currently doesn't work in windows, haven't tested anything else. 

How set are you on pytest? I've only worked with nose in the past, but they look fairly similar (and nose is actually forked from an early version of pytest AFAIK).

**Comment by Fitblip** [comment]
To clarify a bit:

```
C:\Users\fitblip\Documents\GitHub\virustotal2>python setup.py test
running test
running egg_info
writing virustotal2.egg-info\PKG-INFO
writing top-level names to virustotal2.egg-info\top_level.txt
writing dependency_links to virustotal2.egg-info\dependency_links.txt
reading manifest file 'virustotal2.egg-info\SOURCES.txt'
writing manifest file 'virustotal2.egg-info\SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by Phillipmartin** [comment]
I don't have a windows box handy, but I fixed setup.py and the tests, give it a try now.

**Comment by Phillipmartin** [comment]
I'm going to go ahead and close as this appears to work for me now.  let me know if it fails for you.

**Comment by Fitblip** [comment]
Confirmed fixed. Thanks dude! :)
